### PR TITLE
Merge pull request #13 from Sheriefshabaa/main

### PR DESCRIPTION
**Pull request by dohaelsawy**
update the following:
- modified the show result api after each classified image operation with the needed data 
- added makefile file to memorized the important command i wrote and need 
- removed the cases pictures from the media

### CODE REVIEW

**Review by Sheriefshabaa — COMMENTED** [review]
The changes are zero, are you sure that you've done any updates?

**Review by ibrahimkayroky — COMMENTED** [review]
latest

**Review by ibrahimkayroky — APPROVED** [review]
approve

**Review by Sheriefshabaa — COMMENTED** [review]
Om deh sho8lana m3ak ya3am!!!

**Pull request merged**
